### ISSUE TITLE
Importing vue-materials from npm fails

### ISSUE THREAD

**Issue by nolds9** [johnleider/vue-materials#1]
Hi there, currently get the following error in Node console following fresh install and config.
```
~/v2-quickstart/node_modules/vue-materials/src/index.js:1
[1] import Components from './components/_index'
[1] ^
[1] ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Node version is 5.5.0 if that makes a difference.

**Comment by johnleider** [comment]
Currently vue-materials assumes you will be using transforming the import with babel.  I'll build the package into a UMD.

**Comment by johnleider** [comment]
This has been fixed with latest release.
