### ISSUE TITLE
Paralax content

### ISSUE THREAD

**Issue by ribsousa** [johnleider/vue-materials#10]
Parallax support content within it
I added, but did not work!

```
<v-parallax src="http://materializecss.com/images/parallax1.jpg">
     <h1>Paralax text</h1>
</v-parallax>
```

**Comment by johnleider** [comment]
Fixed with commit [ceb8a](https://github.com/johnleider/vue-materials/commit/c643101ffb0e38323da0d7583cfc76302c389109).

Published to 1.0.2-rc.1
