### ISSUE TITLE
question about v-text-input and v-bind?

### ISSUE THREAD

**Issue by mygnu** [johnleider/vue-materials#12]
how do you bind the value v-bind='var' doesn't work

**Comment by johnleider** [comment]
The correct syntax would be v-bind:argument.modifier="expression". [Custom Directives](http://rc.vuejs.org/guide/custom-directive.html) on VueJS's documentation should help you further.

**Comment by mygnu** [comment]
still confused about how do I bind a local variabel i.e. `username` to a `<v-text-input>` ??

**Comment by johnleider** [comment]
With v-model, the same as you would with a regular input. v-model="yourVariable".

**Comment by mygnu** [comment]
```
    <div class="input-field">
            <v-text-input name="first"
                        id="first"
                        placeholder="First Name"
                        v-model="myVar" // **doesn't work**
            ></v-text-input>
            <label for="first">First Name</label>
      </div>```

**Comment by johnleider** [comment]
I'll take a look.

**Comment by johnleider** [comment]
This has been fixed. Run
```bash
npm install vue-materials@1.0.2-rc.2
```
and you should be good to go.

**Comment by mygnu** [comment]
works now thanks
