### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by juppdes** [johnleider/vue-materials#15]
In a new project, after installing vue-materials by npm normally I implemented the code below in 

main.js:
          import Vue from 'vue'
          import App from './App'
          import Materials from 'vue-materials'
          Vue.use(Materials
          new Vue({
            el: '#app',
            render: h => h(App)
          })

App.vue:  without "<>"
          template
            div id="app"
              p
                div class="input-field"
                      v-text-input name="first"
                                  id="first"
                                  placeholder="First Name"
                      /v-text-input
                      label for="first" First Name /label
                 /div
              /p
            /div
          /template
          script
          export default { }
          /script

The following error message appears:

Uncaught ReferenceError: $ is not defined  --> vue-materials.min.js?cbdf:2
(anonymous function)	@	vue-materials.min.js?cbdf:2
(anonymous function)	@	vue-materials.min.js?cbdf:1

points in source:  --> .call(this,function(){return $(e.$el).characterCounter()})}

**Comment by johnleider** [comment]
Ty, I'll take a look into it.

**Comment by johnleider** [comment]
Are you including jquery in your index file? It is a requirement for Materialize.css and seems that this is the problem.

**Comment by juppdes** [comment]
Thank you friend, was really just that.
