### ISSUE TITLE
v-checkbox doesn't work with v-on:click event

### ISSUE THREAD

**Issue by zhanghaowx** [johnleider/vue-materials#20]
```
<v-checkbox name="checkbox3" v-on:click="somefunc">Filled In</v-checkbox>
```
when used above code in a vue component
```
methods() {
    somefunc: function() {
        console.log("called")
    }
}
```
The `console.log` never gets hit.

**Workaround**: put `v-on:click` on .input-field
```
<div class="input-field" v-on:click="setLayerVisibility">
    <v-checkbox name="checkbox3">Filled In</v-checkbox>
</div>
```

**Comment by johnleider** [comment]
This is due to Vue 2.0's update to native events that are not explicitly defined in the component. In order to propagate the event, you need to use v-on:click.native.

Documentation: [http://vuejs.org/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on](url)
