### ISSUE TITLE
Cant' use vue-materials

### ISSUE THREAD

**Issue by mfcarneiro** [johnleider/vue-materials#21]
Hi there,

I want to use vue-materials on my project, but I had some problems. 

1. When I install, npm warns me (Could not be the real problem, I guess..):

 ![issue 1](https://cloud.githubusercontent.com/assets/13247083/19770496/3ead7aa4-9c3e-11e6-9098-78332d61c159.png)

2.Already updated node and npm:

![issue 2](https://cloud.githubusercontent.com/assets/13247083/19770973/0ff44a6a-9c40-11e6-950d-67c47f6786bc.png)

 
3.in the archive main.js, I setup vue.use(Materials) (from 'vue-materials') 

4.I use the example on the documentation, only shows:

![issue 3](https://cloud.githubusercontent.com/assets/13247083/19771025/3c8b47ae-9c40-11e6-92d3-ebb85ae0ddbc.png)

Any clues? 

Thanks for the help!

**Comment by johnleider** [comment]
Try

import Vue from 'vue'
import Materials from 'vue-materials'

Vue.use (Materials)

**Comment by mfcarneiro** [comment]
I already did, it's basics. I mentionate this on the third topic

![captura de tela de 2016-10-29 14-03-00](https://cloud.githubusercontent.com/assets/13247083/19831093/82ea7322-9de0-11e6-8896-fc5fc950db6f.png)

**Comment by johnleider** [comment]
I needed to make sure since your example wasn't very clear to me. The npm warnings have nothing to do with vue-materials and will not affect it working. Are you receiving any actual errors when loading your page? Make sure you are including materialize css and js files as those are not part of this package.

**Comment by mfcarneiro** [comment]
Have you deleted my reply?

Where are in the documentation says about the link and script of materialize? i can't found.

I follow your recomendation and now works

Thanks for the help.
