### ISSUE TITLE
Improvement on documentation

### ISSUE THREAD

**Issue by kenng** [johnleider/vue-materials#23]
Hey, thanks for the nice work putting the materialcss features in Vuejs! It's really handy!

Some thought after using it for a while.

- maybe can improve on the documentation:
  * indicate user should include the materialcss javascript and its css file, as this part is not immediately obvious. I thought it will work after Vue.use(Materials).
  * more on example for the usage like for the component event emitted, the 'input'. like we have to define ref=xx on the child component declared, then bind it with this.$refs.xxx.$on('input', handlerMethod). 
  * example with the v-on:click handling with .native... as again it's not immediately obvious for those new to vuejs2

- some future enhancement:
  * the leanModal has been updated to use Modal. So workaround with 
 `$.fn.leanModal = $.fn.modal` 

Just some 2 cents as I think more will be finding this useful! If you need help for the udpate, just let me know!

**Comment by zwarag** [comment]
> indicate user should include the materialcss javascript and its css file, as this part is not immediately obvious. I thought it will work after Vue.use(Materials).

So i need to `npm install materialize-css` ?

**Comment by zhanghaowx** [comment]
> indicate user should include the materialcss javascript and its css file, as this part is not immediately obvious. I thought it will work after Vue.use(Materials).

Same case for me, took a while to realize this.

**Comment by johnleider** [comment]
I'll be working on the documentation in the coming weeks, thank you for your suggestions.

**Comment by johnleider** [comment]
I'm currently updating the documentations with some of the suggestions above. @kenng you mentioned that you would be interested in helping with some of the updates, if you use reddit, send me a dm to /u/zeroskillz.

**Comment by amor520** [comment]
nice

**Comment by oakdays** [comment]
Regarding the documentation, i'm having problems with adding "waves" to a button, as there is an example but not how to actually do it.

**Comment by zhanghaowx** [comment]
@oakdays I think it is more a materializecss question? You can find examples at http://materializecss.com/buttons.html. The basic is add class `waves-effect waves-light` to your btn

**Comment by oakdays** [comment]
Actually i just found how to do it by browsing the mixins. Just added the property :wavesLight="true" to the v-btn and it worked. I guess this should be in the documentation to help people apply waves effect to buttons.
