### ISSUE TITLE
Can you give example how can we use these without webpack?

### ISSUE THREAD

**Issue by eminpala** [johnleider/vue-materials#25]
This is for a special project combined with ASP.NET.

I couldn't figure out and use  Vue.use(Materialize) successfully.

Thanks

**Comment by johnleider** [comment]
Currently vue-materials doesn't have a standalone build, although I don't see why it couldn't. I'll poke around with it tonight.

**Comment by eminpala** [comment]
Ohh Great.. Looking forward to... Thanks!

**Comment by johnleider** [comment]
I have updated the package to work when required into a project through html, as long as Vue has already been included.
