### ISSUE TITLE
Disable default "Choose your options" for other languages.

### ISSUE THREAD

**Issue by j6montoya** [johnleider/vue-materials#29]
I am developing an application in spanish language. But I don't know how change the text "Choose your options" on component  `<v-select>.`

There is some form.

**Comment by johnleider** [comment]
This has been updated with commit [#8532d29](https://github.com/johnleider/vue-materials/commit/8532d29857982b849cb3937c062245dd8eff40a5). Update your package to vue-materials@1.0.5-rc.6 and install. Set the attribute "select-text" on your select to change the default text.
