### ISSUE TITLE
http://johnleider.com/vue-materials-docs/ 

### ISSUE THREAD

**Issue by zhuewizz** [johnleider/vue-materials#3]
Dialog:-->click button-->Toast  
console: build.js:6 Uncaught TypeError: Cannot read property 'keyCode' of undefined

**Comment by johnleider** [comment]
This was introduced with a Vue beta update, I'll take a look at it.

**Comment by johnleider** [comment]
This was introduced with the change to native events in Vue, will take a look at it.

**Comment by johnleider** [comment]
This has been fixed.

[ce9da5b](https://github.com/johnleider/vue-materials/commit/ce9da5bdfa67d47cd79c6da0a8dc8e347da1605d)
