### ISSUE TITLE
v-select doesn't refresh after array has changed.

### ISSUE THREAD

**Issue by eminpala** [johnleider/vue-materials#31]
Try to load the array from rest api. List within the select will not show the loaded data. It remains with the initial list.

**Comment by johnleider** [comment]
Could you please post your vue and vue-materials version. As well, an example of your code?

**Comment by eminpala** [comment]
See attached.

[vue-select.zip](https://github.com/johnleider/vue-materials/files/629621/vue-select.zip)

**Comment by johnleider** [comment]
Fixed with commit [95545fb](https://github.com/johnleider/vue-materials/commit/95545fb80e608125816ffdcb5f22011de3f15a67).
