### ISSUE TITLE
v-progress-circular with flash doesn't work

### ISSUE THREAD

**Issue by zhanghaowx** [johnleider/vue-materials#32]
The example code
```
    <v-progress-circular active red red-flash></v-progress-circular>
```
is same as
```
    <v-progress-circular active red></v-progress-circular>
```

red-flash has no effect at all. The example in http://johnleider.com/vue-materials-docs also has no color changed. Expected to be the same as http://materializecss.com/preloader.html

**Comment by johnleider** [comment]
This is because you are using red along with red flash. They both apply specific classes. If you just use reg-flash by itself, it should work properly. I will update the documentation.
