### ISSUE TITLE
Dynamic reference of modals/dropdowns

### ISSUE THREAD

**Issue by oakdays** [johnleider/vue-materials#34]
Is there a way to reference a modal or dropdown dynamically? For example:

```
<tr v-for="item in array">
  <td>
    {{ array.prop }}
  </td>
  <td>
      <v-btn v-dropdown:DROPDOWN :wavesLight="true">{{ array.anotherPropy }}</v-btn>
      <v-dropdown id="DROPDOWN">
        <li v-for="anotherItem in anotherArray">
          <a @click="doAction(item, anotherItem)">{{ anotherItem.prop }}</a>
        </li>
      </v-dropdown>
  </td>
</tr>
```

The id of the dropdown is not dynamic, thus leading to code issues of repeated "item" nodes.

**Comment by johnleider** [comment]
You should be able to do it like this or some variant:

```
<tr v-for="(item, i) in array">
  <td>
    {{ array.prop }}
  </td>
  <td>
      <v-btn v-dropdown:i :wavesLight="true">{{ array.anotherPropy }}</v-btn>
      <v-dropdown id="i">
        <li v-for="anotherItem in anotherArray">
          <a @click="doAction(item, anotherItem)">{{ anotherItem.prop }}</a>
        </li>
      </v-dropdown>
  </td>
</tr>
```

I'd have to do more testing when I get home.

**Comment by johnleider** [comment]
Was this able to solve your issue?

**Comment by fersnapshot** [comment]
I have the same problem "The ID of the dropdown list is not dynamic".
`
<tr v-for="(item, i) in array">
  <td>
    {{ array.prop }}
  </td>
  <td>
      <v-btn v-dropdown:i :wavesLight="true">{{ array.anotherPropy }}</v-btn>
      <v-dropdown id="i">
        <li v-for="anotherItem in anotherArray">
          <a @click="doAction(item, anotherItem)">{{ anotherItem.prop }}</a>
        </li>
      </v-dropdown>
  </td>
</tr>
`
it does not work

**Comment by johnleider** [comment]
Try v-dropdown="i"

**Comment by fersnapshot** [comment]
Only the first dropdown is seen
https://jsfiddle.net/fersnapshot/rhjn6s35/1/

**Comment by johnleider** [comment]
Pass it dynamically in by using ```v-dropdown="{ value: i }"```
