### ISSUE TITLE
Datetime and time pickers.

### ISSUE THREAD

**Issue by diegoduncan21** [johnleider/vue-materials#35]
Hi John, nice plugin.
Would be nice count with datetime and time picker.

**Comment by johnleider** [comment]
Could you elaborate please?

**Comment by diegoduncan21** [comment]
Sorry, i was supposed that materials already had one datetime and time picker natively.

**Comment by johnleider** [comment]
Yes, Materialize.css has a native date picker. For additional information on this, please navigate [here](http://materializecss.com/forms.html#date-picker).
