### ISSUE TITLE
Components not initializing on load

### ISSUE THREAD

**Issue by sweinertjr** [johnleider/vue-materials#36]
Components are failing to initialize on page refresh. For example, I have a `v-select` that looks like this in my Vue component:

`
            <v-select v-model="newInstruction.action" name="action" id="action" :items="actionOptions"></v-select>
            <label for="action">Choose..</label>
`
If I refresh the page, it doesn't initialize. The materialize component only initializes properly if I load the Vue component after my Vue app is already loaded.

For example, if I am on `/home` and then I click into my `/login-form` it works. However, if I just start on `/login-form` then the dropdown won't initialize.

I am using https://github.com/vuejs/vue-router - I'm not sure if that is relevant.

**Comment by johnleider** [comment]
Could you please post an example of your index.html and app.js.
