### ISSUE TITLE
Modals are broken in materializecss 0.97.8

### ISSUE THREAD

**Issue by zhanghaowx** [johnleider/vue-materials#38]
Just want let you know that the in the latest version of materializecss 0.97.8

v0.97.8 (October 30th)
-    **Refactored Modal plugin**
-    Tabs now supported in navbar
-    Chips data can now be reinitiailized
-    Minor side nav fixes
-    FAB to toolbar component added
-    Fixed dropdown options bug

The **Refactored Modal plugin** breaks v-modal. I saw errors `Uncaught TypeError: $(...).leanModal is not a function`.

**Comment by johnleider** [comment]
I'm looking at this and not able to reproduce errors with 0.97.8. Could you provide an example of this happening?

**Comment by njirap** [comment]
Hi @johnleider I confirm that I also have this error.

Materialize 0.97.8 no longer uses `leanModal`

What do you need as an example? Source code?

**Comment by johnleider** [comment]
Any type of jsfiddle or codepen would suffice.

**Comment by njirap** [comment]
OK lemmie work on it..

**Comment by rayoplateado** [comment]
Hi guys! any news on this?

**Comment by njirap** [comment]
@rayoplateado a JS fiddle is coming right up!

**Comment by njirap** [comment]
@johnleider https://jsfiddle.net/oo30yt66/3/

**Comment by johnleider** [comment]
Thank you. Sorry for the slow updates. I am extremely busy with my other project, vuetify. I will dedicate some time to come and clear up all the outstanding issues in this repo.
