### ISSUE TITLE
Listening to Modal close event

### ISSUE THREAD

**Issue by nurolopher** [johnleider/vue-materials#39]
Hello,

Thanks for an amazing job!
I would like to know how to listen to modal close events. Did `<v-modal id="modal" v-on:close="close">` but no luck.

Regards,

Nursultan Turdaliev

**Comment by johnleider** [comment]
VModal only emits an event when its methods are used to open/close. If it is closed by Materialize.css, you need to pass your callback into the options parameter. Referenced [here](http://materializecss.com/modals.html#options).
