### ISSUE TITLE
Button page in docs doesn't show waves props

### ISSUE THREAD

**Issue by oakdays** [johnleider/vue-materials#41]
Waves props, like wavesLight and wavesCircle for example, are not described in the documentation's Button page. I think it should be there, as all other props are. I think that a Waves section in the Button page should do the trick, describing all waves properties as booleans.

**Comment by Signorini** [comment]
How to put waves into buttons ?

**Comment by oakdays** [comment]
@Signorini I was able to put waves using :wavesLight="true", for example. You can find out the other methods by browsing the mixins, but this should be in the Button documentation.

**Comment by oakdays** [comment]
@johnleider Can i help somehow?

**Comment by johnleider** [comment]
@oakdays Most definitely. Doc updates or minor bug fixes.

**Comment by oakdays** [comment]
@johnleider I submitted a pull request to the docs.

**Comment by johnleider** [comment]
Merged.
