### ISSUE TITLE
Vel is not a function

### ISSUE THREAD

**Issue by simon-tannai** [johnleider/vue-materials#42]
Hi !

I'm trying to display a Toast, throw from method.
My simple code: 
```
if (this.aoName === '' || this.aoName.length <= 0) {
  this.$dialog('test')
}
```

But I get an error:

> Uncaught TypeError: Vel is not a function
>     at Object.Materialize.toast (eval at <anonymous> (app.js:762), <anonymous>:8:16164)
>     at n (eval at <anonymous> (app.js:930), <anonymous>:2:10739)
>     at VueComponent.sendForm (eval at 88 (0.2095494….hot-update.js:6), <anonymous>:24:14)
>     at Proxy.boundFn (eval at <anonymous> (app.js:600), <anonymous>:126:14)
>     at Object.click [as fn] (eval at <anonymous> (app.js:1028), <anonymous>:52:13)
>     at HTMLButtonElement.eval (eval at <anonymous> (app.js:600), <anonymous>:2748:16)

My import:
```
import jQuery from 'jquery/dist/jquery.min.js'
import 'materialize-css/dist/js/materialize.min.js'
import 'materialize-css/dist/css/materialize.min.css'
import Materials from 'vue-materials'
```

Maybe I forget something ... but what ?

**Comment by johnleider** [comment]
Could you please provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.
