### ISSUE TITLE
Checkbox multiple

### ISSUE THREAD

**Issue by boyfinal** [johnleider/vue-materials#43]
I want get all value input checked to array?
Thanks!

**Comment by johnleider** [comment]
Please follow the <a href="https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md">guidelines</a> on how to report an issue. In particular, provide an example on <a href="https://jsfiddle.net/">www.jsfiddle.net</a> (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Thank you.

**Comment by boyfinal** [comment]
Example:
    ...
   <v-checkbox v-for="item in products" name="itemID" v-bind:value="item.id" v-model="checked">{{ item.name }}</v-checkbox>
    ...
   data () {
		return {
			products: [{id: 1, name: 'apple'}, {id: 2, name: 'samsung'}, {id: 3, name: 'Nokia'} }],
			checked: []
		}
	}
   ...
I need return array value checked.
thank.

**Comment by johnleider** [comment]
Try ```<v-checkbox v-for="item in products" :name="item.id" :value-v="item.id" v-model="checked">{{ item.name }}</v-checkbox>```
