### ISSUE TITLE
v-model on v-select not update their value

### ISSUE THREAD

**Issue by j6montoya** [johnleider/vue-materials#45]
v-model on v-select not update their value

Example

```
myitems = [{id:1,text:1,id:2,text:2}]
```

```
<button @click="click">Update mymodel</button>
<v-select v-model="mymodel" :items="myitems"></v-select>
```

```
click () { this.mymodel = 2 }
```

Thanks!

**Comment by travisbotello** [comment]
The same problem also occurs when using v-checkbox. Binding only works in one direction. When using a method for updating the model (e.g. reset forms after submission) v-select and v-checkbox are not being updated in the dom. 

Quick fix for v-select is calling `$('select').material_select()` once the model was updated.

You can also wrap it with vue.nextTick to make sure dom is ready:

```
Vue.nextTick(function () {
     $('select').material_select();
})
```

**Comment by travisbotello** [comment]
Adding `v-date-input` to this issue as well. Maybe I am missing something here in general or this issue occurs with a couple of form components. 

In my example `v-date-input` is attached to a v-model that is receiving data from an ajax call once a modal is opened. In vue-devtools I can see that the value is updated on the `v-date-input `accordingly but the date on the actual element is not updated...meaning the dom/view is not refreshing.

This is exactly the same with `v-select` and `v-checkbox` (didn't test the rest). Value gets updated according to model changes but the dom is not updated...

**Comment by travisbotello** [comment]
This issue is still not resolved...however here is an example of a materialize select box that is updating its view in both directions. (user <=> data) Unfortunately I am not having the time right now to incorporate this into vue-materialize but maybe this can be used as a starting point:

http://stackoverflow.com/a/40115900/997951
