### ISSUE TITLE
Don't understand how to pass options to v-modal

### ISSUE THREAD

**Issue by rayoplateado** [johnleider/vue-materials#46]
I've read a lot of closed issues, tried millions of different ways, checked documentation, watched source code... I don't understand how can i set opacity, or dismissible options in a v-modal.

Can you please give me some light on this?

Thank you!

**Comment by rayoplateado** [comment]
I think it should be like this:

```
<v-modal id="privacy" :params="modalParams">
            <div slot="content">
                <h4>Modal Header</h4>
                <p>A bunch of text</p>
            </div>
            <div slot="footer">
                <v-btn-link class="pull-right" waves-light modal flat>Disagree</v-btn-link>
                <v-btn-link class="pull-right" waves-light modal flat>Agree</v-btn-link>
            </div>
        </v-modal>
```

and in data:

```
 modalParams: {
        dismissible: true,
        opacity: 0.5,
      },
```

But it's not working...

**Comment by rayoplateado** [comment]
A little bit more of light. Now, changed modalParams as a function into computed:

```
computed: {
  ...mapGetters([
    'authToken',
  ]),
  modalParams() {
    const params = {
      opacity: 0.5,
      dismissible: true,
    };
    return params;
  },
},
```
Then, I can see this in dev Tools:

![image](https://cloud.githubusercontent.com/assets/1727368/22549320/151d0768-e94b-11e6-9d91-57a4fe20ff9d.png)

But my modal seems not to apply this params...

![image](https://cloud.githubusercontent.com/assets/1727368/22549353/3e838aaa-e94b-11e6-9714-0a937b076d74.png)

**Comment by johnleider** [comment]
Params are passed through the v-modal directive. Whichever element you bind to it will pass them.

```
<v-btn v-modal:modal="{ value: modalParams }">Modal</v-btn>
```

**Comment by rayoplateado** [comment]
@johnleider Thank you for answering my issue.

another one.

Where are you defining modalParams in this example? I've tried in computed as a function. I can see params inside the modal in vue dev tools (as the image above) but still doesn't recognizing it...

```
<template>
<div class="check-field col s12">
  <input type="checkbox" name="terms" class="filled-in" id="terms" checked='true' />
  <label for="agree">I agree to the <v-btn-link v-modal:privacy="{ value: modalParams }">privacy policy</v-btn-link> and <a href="#terms">terms & conditions</a></label>
 </div>
 <v-modal id="privacy" :params="modalParams">
            <div slot="content">
                <h4>Modal Header</h4>
                <p>A bunch of text</p>
            </div>
            <div slot="footer">
                <v-btn-link class="pull-right" waves-light modal flat>Disagree</v-btn-link>
                <v-btn-link class="pull-right" waves-light modal flat>Agree</v-btn-link>
            </div>
        </v-modal>
</div>
</template>

<script>

  export default {
    name: 'signupForm',

    data: () => ({
      user: { type: Object, default: {} },
      success: false,
      errorId: null,
    }),


    computed: {
      modalParams() {
        const params = {
          dismissible: true, // Modal can be dismissed by clicking outside of the modal
          opacity: 0.5, // Opacity of modal background
          ready: () => console.log('ready'),
        };
        return params;
      },
  };
</script>
```

**Comment by rayoplateado** [comment]
Here you have a jsfiddle where you can see i'm passing dismissible: true but the modal is not dismissible at all...

https://jsfiddle.net/z11fe07p/503/

**Comment by dzava** [comment]
materialize [renamed `leanmodal`](https://github.com/Dogfalo/materialize/commit/4984e2391fa7ce428d77910c2656835c021d11be) as you can see the overlay class was renamed to `.modal-overlay` but the modal component is not updated so either wait for an update or use version 0.97.6 of materialize.

Use the following to pass options to the modal
```
<v-btn-link v-modal:privacy="modalParams">privacy policy</v-btn-link>
```

**Comment by rayoplateado** [comment]
the jsfiddle is using 0.97.6 but doesn't work.

This jsfiddle do the things as you said, but still not working.

https://jsfiddle.net/rayoplateado/rq0q3fro/

**Comment by dzava** [comment]
It's using version 0.98 of the css though.

**Comment by rayoplateado** [comment]
Man. YOU SAVE MY DAY!

**Comment by johnleider** [comment]
This has been fixed.
