### ISSUE TITLE
click on v-icon inside a dropdown-button make the entire button dissapears

### ISSUE THREAD

**Issue by rayoplateado** [johnleider/vue-materials#47]
I was trying to understand what's going on.

I've create a fiddle. It seems pretty ugly, but the wrong behavior is there. 

https://jsfiddle.net/rayoplateado/ajpwbmd8/1/

if you run and click on arrow_drop_down, it makes dropdown-button dissapear.

materialize css 0.97.6
materialize js 0.97.6

**Comment by rayoplateado** [comment]
More info.

If I remove materials-icons from <i> class, doesn't show the icon, obviously, but the behavior is correct.

**Comment by rayoplateado** [comment]
@johnleider, any clue on this?

**Comment by johnleider** [comment]
This seems to be fixed with 0.98 materialize.
