### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by CoveTechnologyAus** [johnleider/vue-materials#5]
Hi

I am testing vue-materials and am recieving the following console error. I am assuming this does not require jquery. Do you have any ideas? (I am using Vue 2.0RC2)

Note: everything seems to be working - just getting this error in the console.

Chrome Console:
vue-materials.min.js:2Uncaught ReferenceError: $ is not defined

**Comment by CoveTechnologyAus** [comment]
Upon further investigation, if I include jQuery the error changes to:
vue-materials.min.js:2Uncaught TypeError: $(...).dropdown is not a function

I only have the following component on the page at this point and have included ``` Vue.use(Materials) ``` in my main.js.
```
<template>
    <div>
        <v-nav>
            <a href="#!" class="brand-logo" slot="logo">Logo</a>
            <ul class="right">
                <li>
                    <a href="#!"><v-icon>done</v-icon></a>
                </li>
                <li>
                    <a href="#!"><v-icon>list</v-icon></a>
                </li>
                <li>
                    <a href="#!" v-dropdown:v-icon-drop><v-icon>more_vert</v-icon></a>
                </li>
            </ul>
            <v-side-nav id="side2" slot="side-nav"></v-side-nav>
        </v-nav>
        <dropdown id="v-icon-drop">
            <li>
                <a href="#!">Click me</a>
            </li>
            <li>
                <a href="#!">Click me</a>
            </li>
            <li>
                <a href="#!">Click me</a>
            </li>
        </dropdown>
    </div>
</template>
```

**Comment by CoveTechnologyAus** [comment]
Ok I have found that this solution requires the actual Material-CSS library (css, js and jquery) to be included in the App. I have fixed this and all is working now. Closing.

**Comment by stephane** [comment]
The issue about 'dropdown' -> 'v-dropdown' still there in the documentation site.

**Comment by stephane** [comment]
```
new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
        "window.jQuery": "jquery",
        Hammer: "hammerjs/hammer"
    })
```

in the plugins list on my webpack conf do the trick for me.
