### ISSUE TITLE
Modal Does Not Receive Loop Values

### ISSUE THREAD

**Issue by DiegusMiestro** [johnleider/vue-materials#53]
Hello,

I'm trying to use a modal. With a fixed value it works normally, but I need to insert values dynamically. I can not pass the value to the v-modal in v-btn-link. Here's an example in JsFiddle

https://jsfiddle.net/diegusmiestro/2jxpa363/

**Comment by johnleider** [comment]
You can now do this with ```v-modal="{ value: 'your value' }"```

**Comment by sierrakilo** [comment]
Any chance of an example on how to use the ready function?
I have this working:
<v-btn-link v-modal:modal-assignment="{ ready: modalAssignmentOpen('1', item.itemType.code, item.itemNumber) }">-- Assign Student --</v-btn-link>
which calls my function but I need to get the modal as per docs on materialise website
So i tried this:
<v-btn-link v-modal:modal-assignment="{ ready: function(modal, trigger) { console.log('modal', modal) } }">-- Assign Student --</v-btn-link>
But no success.
Many thanks.
