### ISSUE TITLE
Modal doesn't open

### ISSUE THREAD

**Issue by mfcarneiro** [johnleider/vue-materials#54]
I'm implementing on my site a modal, I just do a copy and paste to try out but this component aren't working, I guess..

![modaerror](https://cloud.githubusercontent.com/assets/13247083/23473919/b6f97fd0-fe90-11e6-8a46-cd3af9913895.png)

**Comment by zhanghaowx** [comment]
I filed a bug https://github.com/johnleider/vue-materials/issues/38 about this, as a workaround, you should use materializecss < v0.97.8

**Comment by mfcarneiro** [comment]
Yep, I realize that searching on the documentation again.

I want to now if is possible, this vue-materials will be continued? or I will need to use the vuetify?

I have a site working with this vue-materials and for now, I don't want to change.

Thanks for the reply!

**Comment by johnleider** [comment]
I know that I need to get back in here but I am just extremely busy. I will try to carve out some time to get one last round of bug fixes and compatibility with the newest version of materializecss.

**Comment by mfcarneiro** [comment]
No problem John,

I guess this first material layout is more beautiful than vuetify, follows more material design guidelines.

I'm wondering because using vuetify I will need more work to fix my webpage. I really like your work here, glad to know that you will improve and continue.

Thanks for your time guys!

**Comment by johnleider** [comment]
What do you mean the first material layout? Vuetify is actually written 100% to MD spec. The areas that were missed are being properly updated and almost all are being resolved as of next release. I suppose I don't understand your comment.

**Comment by mfcarneiro** [comment]
Just a Thought John, 

When I mean first material, it's vue-materials instead haha.

For me, vue-materials is more beautiful than vuetify comparing the documentations examples, just it..

**Comment by johnleider** [comment]
I'm not trying to convince you to use Vuetify, I'm simply more focused on that project than this.

**Comment by mfcarneiro** [comment]
I know man,

I just telling what I'm thinking..
