### ISSUE TITLE
Click Event Not Working on Button

### ISSUE THREAD

**Issue by nsang92** [johnleider/vue-materials#7]
Trying to bind a click event to a button, and it is not being registered.

Does not work:
`<v-btn @click="clickTest">
            <v-icon>keyboard_arrow_up</v-icon>
        </v-btn>`

Works:
`<button @click="clickTest">
            <v-icon>keyboard_arrow_up</v-icon>
        </button>`

**Comment by nsang92** [comment]
click.native works

**Comment by johnleider** [comment]
Vue 2.0 components that do not have explicitly defined events must use .native as you have already posted.
