### ISSUE TITLE
Usage with lazy loaded routes

### ISSUE THREAD

**Issue by jeffcj** [johnleider/vue-materials#8]
Hello,
   Was not able to get this to work with vue-router + lazy loaded routes. I believe it is because the materializecss.js binds a number of items on document.ready. I realize this issue is external to the core vue-materials module, but any thoughts on how it could be adapted to support lazy loaded routes?

Thanks!
Jeff

**Comment by johnleider** [comment]
Could you provide an example of your usage so I can address your issue? Thank you!

**Comment by johnleider** [comment]
After doing a little bit of research, the best way for you to handle this would be to manually call the materializecss.js methods after load that you need.  All of the vue-material components that use js from materializecss should automatically do this for you, regardless of when they are loaded.

If this does not address your issue, please open a new ticket.
