### ISSUE TITLE
Modal directive does not pass parameters correctly

### ISSUE THREAD

**Issue by cristianstenico** [johnleider/vue-materials#9]
I think there is an error on the modal directive in passing parameters to the modal.
the call is
`$(el).leanModal(binding.expression || {})`
but according to the documentation ([here](https://rc.vuejs.org/guide/custom-directive.html#Directive-Hook-Arguments)), 'expression' attribute is a string, not an object.
So, if I define a modal call in this way:
`<v-btn v-modal:id="{dismissible: false}">Click me</v-btn>`
the parameter does not work.
Instead, using the 'value' attribute in the call, it simply works.

**Comment by johnleider** [comment]
I'll look into this.  In my testing, the expression was converting object strings into object literals.

**Comment by cristianstenico** [comment]
Maybe I've done something wrong, but in my case I see the correct behaviour only using binding.value.

Also, is there a way to capture the closing event?
I've seen that the component on the 'close' method emits the 'close' event, but I can't capture it on parent component with `<v-model @close="someFunction"></v-model>`.
Thank you.

**Comment by johnleider** [comment]
I'll check that out as well.

**Comment by johnleider** [comment]
The open and close methods are there if you want to manually open or close the modal through other actions and then capture when the action happens.  The proper method for capturing close event natively

**Comment by rayoplateado** [comment]
Hey @cristianstenico, can you please help me out with this issue? https://github.com/johnleider/vue-materials/issues/46 is related to this one. @johnleider has answered me and give me a clue, but I still blocked...
